version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pulsar-man-db
    environment:
      POSTGRES_DB: pulsar
      POSTGRES_USER: pulsar_user
      POSTGRES_PASSWORD: pulsar_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: